### ISSUE TITLE
Load times are way too long

### ISSUE THREAD

**Issue by pilcrowOnPaper** [mattcroat/joy-of-code#47]
Some posts are taking 5 seconds to load. Because cacheing is enabled, load times significantly improve afterward but I don't see any reasons not to prerender pages. Fetch files using Vite's `import.meta.glob()` during build step and pre-rendering pages should make the website feel much more snappier. As for the view count in `/`, it could be fetched in the client (via an endpoint or directly).

**Comment by mattcroat** [comment]
> Some posts are taking 5 seconds to load.

That's unfortunately because Vercel doesn't respect cache-control headers and the cache lasts a couple of hours at most from my experience but I'm fine with that considering the benefits of SSR and the more people use the site the faster it gets.

> I don't see any reasons not to prerender pages.

I'm using an editor to make changes to content and using prerendering I would have to rebuild the entire site after making a change which I do often.

I used SSG in the past and I'm not a fan of it for said reasons and it limits what you can do in the future like user authentication which is an awful experience so I think the solution is to move to a proper CDN.  

> As for the view count in /, it could be fetched in the client (via an endpoint or directly).

I should probably do that! 😄

**Comment by pilcrowOnPaper** [comment]
Gotcha, 

I get why you don't want to pre-render pages, but I don't see why rebuilding the site every time is a bad idea. Vercel gives 6,000 minutes of build execution, which should be enough to rebuild the site 100 times per day. It seems better to use Vite's `import.meta.glob()` to import the markdown files during build time so you don't have to wait for Github's API to fetch the data.

Also, is it possible to add `sveltekit:fetch` to anchor tags to pre-fetch the pages?

**Comment by mattcroat** [comment]
> I don't see why rebuilding the site every time is a bad idea.

I don't want to rebuild the entire site for a simple typo fix for marginal gains and introduce downsides I mentioned even if I could use incremental static regeneration because that experience sucks in my opinion. 

>  I feel its better to import the markdown files during build time so you don't have to wait for Github's API to fetch the data.

It's not the GitHub API but the Markdown processing on the server which is noticeable for large posts but negligible for regular posts and I'm fine with it because a popular post is going to be cached regardless of Vercel's mischief.

I don't think it's a huge issue but in that case I would rather host it elsewhere and use the edge where SSR performance beats everything else.  

> Also, is it possible to add sveltekit:fetch to anchor tags to pre-fetch the pages?

For sure! That would help the perceived speed. I don't remember why I removed it but I'm going to look into it again when I have more time.

I haven't done updates in a while due to the volatile nature of breaking changes where in one instance an update would break the deployment and that's a large reason why I haven't updated but I hope those problems got resolved.

Hope that answers your questions!
